// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoGroup1.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveEncRotations.h"
#include "Commands/DriveEncVelocity.h"
#include "Commands/DriveStop.h"
#include "Commands/DriveWithJoy.h"
#include "Commands/ResetEncoders.h"
#include "Commands/RunMotionProfile.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    xbox.reset(new frc::Joystick(0));
    
    y.reset(new frc::JoystickButton(xbox.get(), 4));
    y->WhenPressed(new DriveEncVelocity());
    x.reset(new frc::JoystickButton(xbox.get(), 3));
    x->WhenPressed(new ResetEncoders());
    b.reset(new frc::JoystickButton(xbox.get(), 2));
    b->WhenPressed(new DriveEncRotations());
    a.reset(new frc::JoystickButton(xbox.get(), 1));
    a->WhenPressed(new RunMotionProfile());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("AutoGroup1", new AutoGroup1());
    frc::SmartDashboard::PutData("DriveEncVelocity", new DriveEncVelocity());
    frc::SmartDashboard::PutData("ResetEncoders", new ResetEncoders());
    frc::SmartDashboard::PutData("DriveStop", new DriveStop());
    frc::SmartDashboard::PutData("DriveEncRotations", new DriveEncRotations());
    frc::SmartDashboard::PutData("RunMotionProfile", new RunMotionProfile());
    frc::SmartDashboard::PutData("DriveWithJoy", new DriveWithJoy());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getxbox() {
   return xbox;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
