// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "WPILib.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::drivetrainfrontleft;
std::shared_ptr<WPI_TalonSRX> RobotMap::drivetrainrearleft;
std::shared_ptr<WPI_TalonSRX> RobotMap::drivetrainfrontright;
std::shared_ptr<WPI_TalonSRX> RobotMap::drivetrainrearright;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

/*Constants

const int kTimeoutMs = 10; //Talon timeout default

const int kSlotIDx_CLoop = 0; //Talon controller slot for CL

const int kSlotIDx_Motion = 1; //Talon controller slot 1 for MP

const int kSensorUnitsPerRotation = 80; //CIMcoder 4 * 20 pulses

/*Closed Loop PID_F constants

const double kF_CLoopLeft = 0.0;

const double kP_CLoopLeft = 6.39375;

const double kI_CLoopLeft = 0.0;

const double kD_CLoopLeft = 639.375;

const double kF_CLoopRight = 0.0;

const double kP_CLoopRight = 6.39375;

const double kI_CLoopRight = 0.0;

const double kD_CLoopRight = 639.375;


/*Motion Profile PID_F constants

const double kF_MotionLeft = 2.379;

const double kP_MotionLeft = 0.0;

const double kI_MotionLeft = 0.0;

const double kD_MotionLeft = 0.0;

const double kF_MotionRight = 2.109;

const double kP_MotionRight = 0.0;

const double kI_MotionRight = 0.0;

const double kD_MotionRight = 0.0;

*/

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    drivetrainfrontleft.reset(new WPI_TalonSRX(0));
    
    
    drivetrainrearleft.reset(new WPI_TalonSRX(1));
    
    
    drivetrainfrontright.reset(new WPI_TalonSRX(2));
    
    
    drivetrainrearright.reset(new WPI_TalonSRX(3));
    
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    /*Set up the talons */

    drivetrainrearleft->Follow(*drivetrainfrontleft); //rear left to follow front left

    drivetrainrearright->Follow(*drivetrainfrontright); //rear right to follow front right

    /*Set up the encoders */

    drivetrainfrontleft->SetSensorPhase(true); //reverse sensors?


    drivetrainfrontright->SetSensorPhase(true); //reverse sensors?

    drivetrainfrontright->SetInverted(true);
    drivetrainrearright->SetInverted(true);

    drivetrainfrontleft->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder, 0, kTimeoutMs); //Set the talons to use quad encoders
    drivetrainfrontright->ConfigSelectedFeedbackSensor(FeedbackDevice::QuadEncoder,0,kTimeoutMs);


    /* Configure PID_F for Closed Loop */

    drivetrainfrontleft->Config_kF(kSlotIDx_CLoop, kF_CLoopLeft, kTimeoutMs);
    drivetrainfrontleft->Config_kP(kSlotIDx_CLoop, kP_CLoopLeft, kTimeoutMs);
    drivetrainfrontleft->Config_kI(kSlotIDx_CLoop, kI_CLoopLeft, kTimeoutMs);
    drivetrainfrontleft->Config_kD(kSlotIDx_CLoop, kD_CLoopLeft, kTimeoutMs);


    drivetrainfrontright->Config_kF(kSlotIDx_CLoop, kF_CLoopRight, kTimeoutMs);
    drivetrainfrontright->Config_kP(kSlotIDx_CLoop, kP_CLoopRight, kTimeoutMs);
    drivetrainfrontright->Config_kI(kSlotIDx_CLoop, kI_CLoopRight, kTimeoutMs);
    drivetrainfrontright->Config_kD(kSlotIDx_CLoop, kD_CLoopRight, kTimeoutMs);

    /*Configure PID_F for Motion Profile */

    drivetrainfrontleft->Config_kF(kSlotIDx_Motion, kF_MotionLeft, kTimeoutMs);
    drivetrainfrontleft->Config_kP(kSlotIDx_Motion, kP_MotionLeft, kTimeoutMs);
    drivetrainfrontleft->Config_kI(kSlotIDx_Motion, kI_MotionLeft, kTimeoutMs);
    drivetrainfrontleft->Config_kD(kSlotIDx_Motion, kD_MotionLeft, kTimeoutMs);


    drivetrainfrontright->Config_kF(kSlotIDx_Motion, kF_MotionRight, kTimeoutMs);
    drivetrainfrontright->Config_kP(kSlotIDx_Motion, kP_MotionRight, kTimeoutMs);
    drivetrainfrontright->Config_kI(kSlotIDx_Motion, kI_MotionRight, kTimeoutMs);
    drivetrainfrontright->Config_kD(kSlotIDx_Motion, kD_MotionRight, kTimeoutMs);



}
