// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Drivetrain.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/driveWithJoy.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Drivetrain::Drivetrain() : frc::Subsystem("Drivetrain") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    frontleft = RobotMap::drivetrainfrontleft;
    rearleft = RobotMap::drivetrainrearleft;
    frontright = RobotMap::drivetrainfrontright;
    rearright = RobotMap::drivetrainrearright;
    robotdrivecontroller = RobotMap::drivetrainRobotdrivecontroller;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void Drivetrain::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new driveWithJoy());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Drivetrain::Periodic() {
    // Put code here to be run every loop

}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Drivetrain::Drive(std::shared_ptr<frc::Joystick>xbox){
	if(xbox->GetRawButton(6)==1){
		robotdrivecontroller->TankDrive(0.6*xbox->GetRawAxis(5), 0.6*xbox->GetRawAxis(1));
	}
	else if(xbox->GetRawAxis(2)==1){
		robotdrivecontroller->TankDrive(-.5*xbox->GetRawAxis(1), -.5*xbox->GetRawAxis(5));
	}
	else{
		robotdrivecontroller->TankDrive(-1*xbox->GetRawAxis(1), -1*xbox->GetRawAxis(5));
	}
}

