// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "ctre/Phoenix.h"
#include "WPILib.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::chassisSubfrontLeft;
std::shared_ptr<SpeedController> RobotMap::chassisSubrearLeft;
std::shared_ptr<SpeedController> RobotMap::chassisSubfrontRight;
std::shared_ptr<SpeedController> RobotMap::chassisSubrearRight;
std::shared_ptr<RobotDrive> RobotMap::chassisSubDriveTrian;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    chassisSubfrontLeft.reset(new VictorSP(0));
    lw->AddActuator("ChassisSub", "frontLeft", std::static_pointer_cast<VictorSP>(chassisSubfrontLeft));
    
    chassisSubrearLeft.reset(new VictorSP(1));
    lw->AddActuator("ChassisSub", "rearLeft", std::static_pointer_cast<VictorSP>(chassisSubrearLeft));
    
    chassisSubfrontRight.reset(new VictorSP(2));
    lw->AddActuator("ChassisSub", "frontRight", std::static_pointer_cast<VictorSP>(chassisSubfrontRight));
    
    chassisSubrearRight.reset(new VictorSP(3));
    lw->AddActuator("ChassisSub", "rearRight", std::static_pointer_cast<VictorSP>(chassisSubrearRight));
    
    chassisSubDriveTrian.reset(new RobotDrive(chassisSubfrontLeft, chassisSubrearLeft,
              chassisSubfrontRight, chassisSubrearRight));
    
    chassisSubDriveTrian->SetSafetyEnabled(true);
        chassisSubDriveTrian->SetExpiration(0.1);
        chassisSubDriveTrian->SetSensitivity(0.5);
        chassisSubDriveTrian->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
